site_name: 0SX - Notes de cours
theme:
  name: material
  language: fr

nav:
  - Accueil: index.md
  - Cours 01: c01/index.md
  - Cours 02:
    - Fonctions de communication: docs/c02/C02_fonctions_comm.md
    - Exercices pratiques: docs/c02/C02_fonctions_comm.md
  - Cours 03: c03/index.md 
  - Cours 04: c04/index.md
  
